### ISSUE TITLE
basic todo's for this repo

### ISSUE THREAD

**Issue by GottZ** [GottZ/url-minimizer#2]
- [ ] take some filters from [DrKain/tidy-url](https://github.com/DrKain/tidy-url/tree/main) and attribute their contribution properly. (check license compatibility first)
- [ ] take from [kmgb/discord-link-cleaner](https://github.com/kmgb/discord-link-cleaner) (check license compatibility first) for more inspiration. they use adguards filter list as data source. it would be reasonable to parse it and add features of it.
- [ ] TikTok (just a random thought. no idea. I don't even use it)
- [ ] Facebook
- [ ] Instagram
- [ ] Twitter
- [ ] find more
- [ ] take from [aenachescu/TrackLess](https://github.com/aenachescu/TrackLess/tree/master) and attribute contribution accordingly to GPL
- [ ] update license for compatibility if necessary
- [ ] add release script
- [ ] add build script
- [ ] add integration into sites, to replace any share buttons with non-tracking links (where applicable) this also has to be kept on monitoring to account for site changes.
- [ ] make it a browser plugin to exit the realm of tampermonkey but keep the tampermonkey plugin alive nontheless.
- [ ] change includes to match for future proofing the script
- [ ] improve site matching. regexp are nice.. ye.. but there are better alternative techniques in my head.
- [ ] add tests with pseudo url's
- [ ] add an issue template for requesting new sites
- [ ] remove host / path / search redundancy
  - [ ] use Elvis operator ( ?. )
- [ ] add Google Search
- [ ] add Google Maps
